/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        navy: {
          '900': '#0A192F',
        },
        gold: {
          '500': '#FFD700',
        },
        'blue-700': '#1C768F',
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#c1c9bd",
        "primary-fixed-dim": "#bdcbb2",
        "tertiary-fixed": "#dde5d9",
        "on-primary": "#ffffff",
        "secondary": "#735854",
        "on-tertiary-fixed-variant": "#414940",
        "on-secondary": "#ffffff",
        "inverse-surface": "#30302e",
        "on-tertiary-fixed": "#161d16",
        "surface-container": "#f0edea",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#2f3c29",
        "on-primary-fixed-variant": "#3e4a37",
        "on-primary-fixed": "#131e0e",
        "on-surface-variant": "#444841",
        "on-background": "#1b1c1a",
        "outline-variant": "#c5c8be",
        "on-tertiary": "#ffffff",
        "primary-container": "#98a68e",
        "surface-tint": "#55624d",
        "tertiary": "#596157",
        "secondary-container": "#ffdad5",
        "on-secondary-fixed-variant": "#59413d",
        "background": "#fbf9f5",
        "inverse-on-surface": "#f3f0ed",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdad5",
        "surface-bright": "#fbf9f5",
        "on-tertiary-container": "#333a32",
        "surface-container-high": "#eae8e4",
        "surface-container-low": "#f6f3f0",
        "surface-variant": "#e4e2df",
        "error-container": "#ffdad6",
        "surface": "#fbf9f5",
        "primary-fixed": "#d9e7cd",
        "on-secondary-container": "#795e5a",
        "primary": "#55624d",
        "on-secondary-fixed": "#2a1614",
        "surface-container-highest": "#e4e2df",
        "surface-dim": "#dcdad6",
        "tertiary-container": "#9ca499",
        "on-surface": "#1b1c1a",
        "on-error-container": "#93000a",
        "outline": "#757870",
        "secondary-fixed-dim": "#e1bfba",
        "inverse-primary": "#bdcbb2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "64px",
        "stack-md": "16px",
        "unit": "8px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["40px", {"lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      },
      animation: {
        'fade-in': 'fadeIn 1s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}